window.CAR_TYPES = [
  {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    tagline: 'Balanced all-rounder',
    asset: 'assets/cars/neon-pulse.png',
    glow: '#00f0ff',
    width: 58,
    height: 76,
    baseSpeed: 6,
    maxSpeedBonus: 9,
    steerMult: 1.05,
    nitroMult: 1.55,
    nitroDrain: 0.78,
    nitroRecharge: 0.34,
    trafficWeight: 2,
    engine: { wave: 'sawtooth', baseFreq: 58, freqScale: 8, nitroBoost: 36, filter: 430, volume: 0.03, nitroVolume: 0.055 },
  },
  {
    id: 'midnight-gt',
    name: 'Midnight GT',
    tagline: 'High top speed, heavy handling',
    asset: 'assets/cars/midnight-gt.png',
    glow: '#8899ff',
    width: 60,
    height: 78,
    baseSpeed: 6.4,
    maxSpeedBonus: 11,
    steerMult: 0.82,
    nitroMult: 1.45,
    nitroDrain: 0.92,
    nitroRecharge: 0.28,
    trafficWeight: 2,
    engine: { wave: 'square', baseFreq: 42, freqScale: 6, nitroBoost: 28, filter: 300, volume: 0.038, nitroVolume: 0.06, harmonic: 84, harmonicWave: 'square', harmonicVol: 0.014 },
  },
  {
    id: 'drift-phantom',
    name: 'Drift Phantom',
    tagline: 'Razor steering for tight curves',
    asset: 'assets/cars/drift-phantom.png',
    glow: '#c86bff',
    width: 62,
    height: 74,
    baseSpeed: 5.9,
    maxSpeedBonus: 8.5,
    steerMult: 1.38,
    nitroMult: 1.5,
    nitroDrain: 0.85,
    nitroRecharge: 0.3,
    trafficWeight: 2,
    engine: { wave: 'triangle', baseFreq: 72, freqScale: 9, nitroBoost: 42, filter: 520, volume: 0.028, nitroVolume: 0.05 },
  },
  {
    id: 'thunder-rex',
    name: 'Thunder Rex',
    tagline: 'Muscle power with brutal nitro',
    asset: 'assets/cars/thunder-rex.png',
    glow: '#ff8c3a',
    width: 64,
    height: 80,
    baseSpeed: 6.1,
    maxSpeedBonus: 9.5,
    steerMult: 0.88,
    nitroMult: 1.85,
    nitroDrain: 1.15,
    nitroRecharge: 0.24,
    trafficWeight: 1,
    engine: { wave: 'sawtooth', baseFreq: 36, freqScale: 5, nitroBoost: 22, filter: 240, volume: 0.042, nitroVolume: 0.07, harmonic: 54, harmonicWave: 'square', harmonicVol: 0.018 },
  },
  {
    id: 'velocity-rx',
    name: 'Velocity RX',
    tagline: 'Lightweight acceleration demon',
    asset: 'assets/cars/velocity-rx.png',
    glow: '#e8f4ff',
    width: 54,
    height: 72,
    baseSpeed: 5.7,
    maxSpeedBonus: 11.5,
    steerMult: 1.18,
    nitroMult: 1.6,
    nitroDrain: 0.88,
    nitroRecharge: 0.33,
    trafficWeight: 2,
    engine: { wave: 'sine', baseFreq: 92, freqScale: 11, nitroBoost: 48, filter: 680, volume: 0.024, nitroVolume: 0.048 },
  },
  {
    id: 'steel-hauler',
    name: 'Steel Hauler',
    tagline: 'Slow van, planted and stable',
    asset: 'assets/cars/steel-hauler.png',
    glow: '#b0c4de',
    width: 68,
    height: 86,
    baseSpeed: 5.1,
    maxSpeedBonus: 6.5,
    steerMult: 0.72,
    nitroMult: 1.25,
    nitroDrain: 0.7,
    nitroRecharge: 0.38,
    trafficWeight: 3,
    engine: { wave: 'sawtooth', baseFreq: 30, freqScale: 4, nitroBoost: 16, filter: 200, volume: 0.035, nitroVolume: 0.05 },
  },
  {
    id: 'crimson-blade',
    name: 'Crimson Blade',
    tagline: 'Pure speed machine',
    asset: 'assets/cars/crimson-blade.png',
    glow: '#ff3355',
    width: 60,
    height: 76,
    baseSpeed: 6.5,
    maxSpeedBonus: 12,
    steerMult: 0.92,
    nitroMult: 1.65,
    nitroDrain: 0.95,
    nitroRecharge: 0.27,
    trafficWeight: 1,
    engine: { wave: 'sawtooth', baseFreq: 66, freqScale: 9, nitroBoost: 44, filter: 500, volume: 0.032, nitroVolume: 0.058, harmonic: 132, harmonicWave: 'triangle', harmonicVol: 0.01 },
  },
  {
    id: 'ghost-walker',
    name: 'Ghost Walker',
    tagline: 'Electric whisper, efficient nitro',
    asset: 'assets/cars/ghost-walker.png',
    glow: '#5dffe8',
    width: 58,
    height: 74,
    baseSpeed: 6.2,
    maxSpeedBonus: 10,
    steerMult: 1.08,
    nitroMult: 1.4,
    nitroDrain: 0.58,
    nitroRecharge: 0.48,
    trafficWeight: 1,
    engine: { wave: 'sine', baseFreq: 118, freqScale: 12, nitroBoost: 55, filter: 900, volume: 0.018, nitroVolume: 0.035, harmonic: 236, harmonicWave: 'sine', harmonicVol: 0.008 },
  },
  {
    id: 'golden-emperor',
    name: 'Golden Emperor',
    tagline: 'Luxury cruiser, smooth control',
    asset: 'assets/cars/golden-emperor.png',
    glow: '#ffd76a',
    width: 60,
    height: 82,
    baseSpeed: 6,
    maxSpeedBonus: 9,
    steerMult: 1,
    nitroMult: 1.5,
    nitroDrain: 0.8,
    nitroRecharge: 0.35,
    trafficWeight: 2,
    engine: { wave: 'triangle', baseFreq: 50, freqScale: 7, nitroBoost: 32, filter: 380, volume: 0.026, nitroVolume: 0.045 },
  },
  {
    id: 'viper-strike',
    name: 'Viper Strike',
    tagline: 'Track bred, fierce and fast',
    asset: 'assets/cars/viper-strike.png',
    glow: '#7dff4f',
    width: 56,
    height: 72,
    baseSpeed: 6.6,
    maxSpeedBonus: 11,
    steerMult: 1.22,
    nitroMult: 1.7,
    nitroDrain: 1,
    nitroRecharge: 0.29,
    trafficWeight: 1,
    engine: { wave: 'sawtooth', baseFreq: 78, freqScale: 10, nitroBoost: 46, filter: 560, volume: 0.03, nitroVolume: 0.056, harmonic: 156, harmonicWave: 'sawtooth', harmonicVol: 0.011 },
  },
];